rcopy: fix UNUSED_VALUE
Error: UNUSED_VALUE (CWE-563):
rdma-core-28.0/librdmacm/examples/rcopy.c:265: value_overwrite: Overwriting previous write to "ret" with value "0".
rdma-core-28.0/librdmacm/examples/rcopy.c:262: assigned_value: Assigning value from "*__errno_location()" to "ret" here, but that stored value is overwritten before it can be used.
|#  260|     if (fd < 0) {
|#  261|         printf("unable to open destination file\n");
|#  262|->       ret = errno;
|#  263|     }
|#  264|

Signed-off-by: Honggang Li <honli@redhat.com>

Orabug: 31331960

(cherry picked from commit 2b25ddd25474b6b63e1c59cd78abc467f4a7dbfe)
cherry-pick-repo=github.com/linux-rdma/rdma-core.git
unmodified-from-upstream: 2b25ddd25474b6b63e1c59cd78abc467f4a7dbfe

Signed-off-by: Mark Haywood <mark.haywood@oracle.com>
Reviewed-by: Håkon Bugge <haakon.bugge@oracle.com>